language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

install: npm install

script: true

deploy:
  - provider: npm
    email: liangrenhong2017@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: production
      tags: on