language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

install: npm install

deploy:
  - provider: pages
    script: npm run build
    skip_cleanup: true
    github_token: $token
    local_dir: build
    on:
      branch: master
  - provider: npm
    email: liangrenhong2017@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: production
      tags: on